name: Lint

on:
  push:
    paths:
      - 'ci/**'
      - 'tests/**'
      - '.github/workflows/**'
      - 'pyproject.toml'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'ci/**'
      - 'tests/**'
      - '.github/workflows/**'
      - 'pyproject.toml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  python:
    name: Python lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff lint
        run: |
          # Check which directories exist before running ruff
          if [ -d "ci" ] || [ -d "scripts" ] || [ -d "tests" ]; then
            ruff check .
          else
            echo "No Python files to check in ci/, scripts/, or tests/ directories"
          fi

  shell:
    name: Shell lint (shellcheck)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          # Only run if there are .sh files in ci/ directory
          if find ci -name '*.sh' | grep -q .; then
            find ci -name '*.sh' -print0 | xargs -0 -r shellcheck
          else
            echo "No shell scripts found in ci/ directory"
          fi
